development:
  adapter: postgresql
  encoding: unicode
  database: altius_development
  pool: 5
  username: postgres
  password: altius
  host: 192.168.1.59
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: altius_test
  pool: 5
  username: postgres
  password: altius
  host: 192.168.1.59
  port: 5432
